/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	/** Add this function **/
	public static void main(String arg[]) {
		System.out.println("hello world");
	}
	
    public boolean someLibraryMethod() {
        return true;
    }
}
